### PR TITLE
Support for Rails 6.1.4.1 and onward (Until 7) + Supporting CI Changes.

### LINKED ISSUE #38: Rails 6.1 Support
I have a rails 6.0 app that uses polymorphic_integer_type 2.2.5. Apparently the latest version 2.3.1 has a dependency of  activerecord < 6 but we've not seen issues so far.

When I upgraded to rails 6.1 recently, I got
```
undefined method `association' for #<ActiveRecord::TableMetadata:0x00007ff3db412018>
```

from this [line](https://github.com/clio/polymorphic_integer_type/blob/2.3.0/lib/polymorphic_integer_type/activerecord_5_0_0/polymorphic_array_value_extension.rb#L5). Changing `:association` to `:reflection` seems to fix the issue. 

I think I can upgrade to polymorphic_integer_type 2.3.1 and try to make the same change to `:reflection` but seeing 2.3.1 doesn't support Rails 6.0, are there any known issues right now with rails 6.0?

### PR DESCRIPTION
**Pull request by Aelphaeis**
Presently we do not have support for rails 6.1.4.1.

The objective of this pull request is to fix tests and ensure that the polymorphic integer type works with rails 6.1.4.1 as well as update CI to test this functionality.

Several tests are broken because https://github.com/rails/rails/pull/40969 & https://github.com/rails/rails/issues/40943 were fixed/closed by https://github.com/rails/rails/commit/b52b8040ff8170118bc8ada43413e5a6d97a778f.
The net effect that the [original replace_keys](https://github.com/rails/rails/blob/1b5658b562b29f8aab7e80cbab8adbd2ddea5447/activerecord/lib/active_record/associations/belongs_to_association.rb#L99-L101
) has been updated to have a [new argument called force ](https://github.com/rails/rails/blob/6-1-stable/activerecord/lib/active_record/associations/belongs_to_association.rb#L110-L116)

I've made some changes to better support continuous integration.

fixes #38

### CODE REVIEW

**Review by rhemsing — APPROVED** [review]
Makes sense to me. Joseph and I chatted through the downsides of not including lock files. I think we're probably fine because of the nature of this gem -- it's very specific functionality that is covered by CI.

**Review by mctaylorpants — APPROVED** [review]

**Review by samsarkleio — APPROVED** [review]

**Review by ChrisNJ58 — APPROVED** [review]
